### ISSUE TITLE
Crawl Website Metadata from Sitemaps

### ISSUE THREAD

**Issue by kshehadex** [Mahdishehady/python-website-analyzer#2]
Follow the steps to get sitemap link from every website:

1. https://www.aljazeera.net/
2. https://www.aljazeera.net/robots.txt
3. https://www.aljazeera.net/sitemap.xml

Use python Beatifualsoap to parse the html of the page and extract the JsonLd and the metadata

**Comment by m-haydar** [comment]
https://www.tutorialspoint.com/beautiful_soup/beautiful_soup_quick_guide.htm

**Comment by m-haydar** [comment]
- **Task Description:** Get familiar with the concept of web scraping and understand the basic working of `requests` and `BeautifulSoup` libraries.
    - **Libraries/Tools:** Python, `requests`, `BeautifulSoup`
    - **Detailing:** Start by reading the official documentation and some basic tutorials on web scraping. Ensure you understand how to send HTTP requests and parse HTML/XML content.
