### ISSUE TITLE
Save Data to MongoDb (Data storage)

### ISSUE THREAD

**Issue by kshehadex** [Mahdishehady/python-website-analyzer#4]

**Comment by m-haydar** [comment]
**Introduction to MongoDB and Data Storage**
    - **Task Description:** Setup MongoDB, familiarize yourself with its basic operations, and store the scraped data.
    - **Libraries/Tools:** MongoDB
    - **Detailing:** Install MongoDB and establish a connection using Python. Understand basic CRUD operations. Save the scraped data in an appropriate collection.

**Comment by m-haydar** [comment]
https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-windows/
