### ISSUE TITLE
Create Some Charts ( Data Visulization)

### ISSUE THREAD

**Issue by kshehadex** [Mahdishehady/python-website-analyzer#6]

**Comment by m-haydar** [comment]
**Data Visualization - Basics**
    - **Task Description:** Learn the fundamentals of data visualization and get introduced to Highcharts and AmCharts.
    - **Libraries/Tools:** Highcharts, AmCharts
    - **Detailing:** Go through the official documentation of both tools. Experiment with basic visualization types using sample data.
**Building the Dashboard using MongoDB Queries**
    - **Task Description:** Use the stored data in MongoDB to create meaningful visualizations using Highcharts or AmCharts.
    - **Libraries/Tools:** MongoDB, Highcharts, AmCharts
    - **Detailing:** Write efficient MongoDB queries to extract the required data. Integrate this data with Highcharts or AmCharts to build your dashboard.

**Comment by Mahdishehady** [comment]
use oop for inheritance and abstract
file naming fix all lower case with _
add commnets in the code
add a readme file and state you working steps
split the code into modules:
Ykon fe service esma mangodb_service be folder services
W folder models
 W folder crawler masalan
6. scrape the data again add new field named word counts to count the words of the content
7. WordCloud for Keywords
8. Bubble chart for Categories
9. Pie Chart for wordcount (0-100 word, 100-200,200-400,>400)
